intents:
  - affirm
  - deny
  - greet
  - goodbye
  - thanks
  - whoareyou
  - whattodo
  - address_inform
  - time_inform
  - schedule_time_inform
  - choose_inform
  - request_trip
  - meeting_book
  - stop
  - not_intent

session_config:
  carry_over_slots_to_new_session: true
  session_expiration_time: 60

slots:
  start_time:
    type: unfeaturized
    auto_fill: false
  end_time:
    type: unfeaturized
    auto_fill: false
  start_address:
    type: unfeaturized
    auto_fill: false
  end_address:
    type: unfeaturized
    auto_fill: false
  task:
    type: unfeaturized
    auto_fill: false
  item:
    type: unfeaturized
    auto_fill: false
  it_item_num:
    type: unfeaturized
    auto_fill: false
  fin_item_num:
    type: unfeaturized
    auto_fill: false
  type:
    type: unfeaturized
    auto_fill: false
  tiaoxian:
    type: unfeaturized
    auto_fill: false
  baoxiaodiqu:
    type: unfeaturized
    auto_fill: false
  baoxiaobumen:
    type: unfeaturized
    auto_fill: false
  receive:
    type: unfeaturized
    auto_fill: false
  ruzhudi:
    type: unfeaturized
    auto_fill: false
  chengjicishu:
    type: unfeaturized
    auto_fill: false
  chuxingren:
    type: unfeaturized
    auto_fill: false
  person_level:
    type: unfeaturized
    auto_fill: false
  banliyijian:
    type: unfeaturized
    auto_fill: false
  nextnode:
    type: unfeaturized
    auto_fill: false
  nextperson:
    type: unfeaturized
    auto_fill: false
  is_affirm:
    type: unfeaturized
    auto_fill: false
  meeting_schedule_time:
    type: unfeaturized
    auto_fill: false
  meeting_start_time:
    type: unfeaturized
    auto_fill: false
  meeting_end_time:
    type: unfeaturized
    auto_fill: false
  meeting_start_date:
    type: unfeaturized
    auto_fill: false
  meeting_end_date:
    type: unfeaturized
    auto_fill: false
  meeting_name:
    type: unfeaturized
    auto_fill: false
  meeting_type:
    type: unfeaturized
    auto_fill: false
  meeting_topic:
    type: unfeaturized
    auto_fill: false
  meeting_room:
    type: unfeaturized
    auto_fill: false
  meeting_zhubanbumen:
    type: unfeaturized
    auto_fill: false
  meeting_msg_remind:
    type: unfeaturized
    auto_fill: false

entities:
  - start_time
  - end_time
  - start_address
  - end_address
  - task
  - item
  - it_item_num
  - fin_item_num
  - type
  - baoxiaodiqu
  - baoxiaobumen
  - tiaoxian
  - receive
  - ruzhudi
  - chengjicishu
  - chuxingren
  - person_level
  - banliyijian
  - nextnode
  - nextperson
  - is_affirm
  - meeting_schedule_time
  - meeting_start_time
  - meeting_end_time
  - meeting_start_date
  - meeting_end_date
  - meeting_name
  - meeting_type
  - meeting_topic
  - meeting_room
  - meeting_zhubanbumen
  - meeting_msg_remind

actions:
  - utter_answer_affirm
  - utter_answer_deny
  - utter_answer_stop
  - utter_answer_greet
  - utter_answer_goodbye
  - utter_answer_thanks
  - utter_answer_whoareyou
  - utter_answer_whattodo
  - utter_answer_abandon
  - utter_answer_other_intent
  - utter_ask_start_time
  - utter_ask_start_address
  - utter_ask_end_time
  - utter_ask_end_address
  - utter_ask_task
  - utter_ask_item
  - utter_ask_it_item_num
  - utter_ask_fin_item_num
  - utter_ask_tiaoxian
  - utter_ask_type
  - utter_ask_baoxiaodiqu
  - utter_ask_baoxiaobumen
  - utter_ask_receive
  - utter_ask_ruzhudi
  - utter_ask_chengjicishu
  - utter_ask_chuxingren
  - utter_ask_person_level
  - utter_ask_banliyijian
  - utter_ask_nextnode
  - utter_ask_nextperson
  - utter_ask_is_affirm
  - utter_ask_abandon
  - utter_ask_continue
  - utter_ask_meeting_schedule_time
  - utter_ask_meeting_start_time
  - utter_ask_meeting_end_time
  - utter_ask_meeting_start_date
  - utter_ask_meeting_end_date
  - utter_ask_meeting_name
  - utter_ask_meeting_topic
  - utter_wrong_start_time
  - utter_wrong_end_time
  - utter_wrong_start_address
  - utter_wrong_end_address
  - utter_wrong_trip_type
  - utter_wrong_baoxiaodiqu
  - utter_wrong_baoxiaobumen
  - utter_wrong_tiaoxian
  - utter_wrong_receive
  - utter_wrong_it_item_num
  - utter_wrong_fin_item_num
  - utter_wrong_nextnode
  - utter_wrong_person_level
  - utter_wrong_chengjicishu
  - utter_wrong_empty_answer
  - utter_wrong_is_affirm
  - utter_jiaoban_success
  - utter_trip_hotel_recommend
  - utter_trip_flight_recommend
  - action_default_fallback
  - action_trip_jiaoban
  - action_trip_hotel_recommend
  - action_trip_flight_recommend
  - action_meeting_jiaoban

forms:
  - trip_form
  - affirm_form
  - meeting_form

responses:
  utter_answer_affirm:
    - text: "嗯嗯，好的！"
    - text: "嗯嗯，很开心能够帮您解决问题~"
    - text: "嗯嗯，还需要什么我能够帮助您的呢？"

  utter_answer_greet:
    - text: "您好！请问我可以帮到您吗？"
    - text: "您好！很高兴为您服务。请说出您要查询的功能？"

  utter_answer_goodbye:
    - text: "再见"
    - text: "拜拜"
    - text: "虽然我有万般舍不得，但是天下没有不散的宴席~祝您安好！"
    - text: "期待下次再见！"
    - text: "嗯嗯，下次需要时随时记得我哟~"
    - text: "see you!"

  utter_answer_deny:
    - text: "主人，您不开心吗？不要离开我哦"
    - text: "怎么了，主人？"
    
  utter_answer_stop:
    - text: "您当前没有正在进行的差旅申请哦"
    - text: "怎么了，主人？"
  
  utter_answer_abandon:
    - text: "已为您放弃本次申请。"
    
  utter_answer_thanks:
    - text: "嗯呢。不用客气~"
    - text: "这是我应该做的，主人~"
    - text: "嗯嗯，合作愉快！"

  utter_answer_whoareyou:
    - text: "您好！我是小兴呀，您的AI智能助理"

  utter_answer_whattodo:
    - text: "您好！很高兴为您服务，我目前支持差旅申请哦。"
  
  utter_answer_other_intent:
    - text: "如需办理其他业务请先输入 放弃申请 退出当前业务办理流程哦"

  utter_ask_start_time:
    - text: "请输入您的出差起始日期，如（2020-06-09）"
  
  utter_ask_end_time:
    - text: "请输入您的出差结束日期，如（2020-06-09）"
    
  utter_ask_start_address:
    - text: "请输入您的差旅出发地"
  
  utter_ask_end_address:
    - text: "请输入您的差旅目的地"
    
  utter_ask_task:
    - text: "请输入您的出行任务"
    
  utter_ask_item:
    - text: "请输入您的项目, 若没有可填'无'"
    
  utter_ask_it_item_num:
    - text: "请输入IT综合管理平台项目编号，如CP[2019]123, 若没有可填'无'"
    
  utter_ask_fin_item_num:
    - text: "请输入财务项目编号，13位数字, 若没有可填'无'"
  
  utter_ask_tiaoxian:
    - text: "请选择您的条线"
      buttons:
        - title: "信用卡中心"
          payload: '/choose_inform{"tiaoxian": "信用卡中心"}'
        - title: "同业"
          payload: '/choose_inform{"tiaoxian": "同业"}'
        - title: "企金"
          payload: '/choose_inform{"tiaoxian": "企金"}'
        - title: "零售"
          payload: '/choose_inform{"tiaoxian": "零售"}'
        - title: "投金"
          payload: '/choose_inform{"tiaoxian": "投金"}'
        - title: "其他"
          payload: '/choose_inform{"tiaoxian": "其他"}'
    
  utter_ask_type:
    - text: "请选择您的出差类型"
      buttons:
        - title: "短期出差"
          payload: '/choose_inform{"type": "短期出差"}'
        - title: "长期出差"
          payload: '/choose_inform{"type": "长期出差"}'
        - title: "研发项目"
          payload: '/choose_inform{"type": "研发项目"}'
        - title: "系统内培训"
          payload: '/choose_inform{"type": "系统内培训"}'
        - title: "系统外培训"
          payload: '/choose_inform{"type": "系统外培训"}'
        - title: "系统内会议"
          payload: '/choose_inform{"type": "系统内会议"}'
        - title: "系统外会议"
          payload: '/choose_inform{"type": "系统外会议"}'
    
  utter_ask_baoxiaodiqu:
    - text: "请选择您的报销地区"
      buttons:
        - title: "福州"
          payload: '/choose_inform{"baoxiaodiqu": "福州"}'
        - title: "上海"
          payload: '/choose_inform{"baoxiaodiqu": "上海"}'
        - title: "北京"
          payload: '/choose_inform{"baoxiaodiqu": "北京"}'
        - title: "成都"
          payload: '/choose_inform{"baoxiaodiqu": "成都"}'
        - title: "武汉"
          payload: '/choose_inform{"baoxiaodiqu": "武汉"}'
        - title: "深圳"
          payload: '/choose_inform{"baoxiaodiqu": "深圳"}'
        - title: "厦门"
          payload: '/choose_inform{"baoxiaodiqu": "厦门"}'
        - title: "广州"
          payload: '/choose_inform{"baoxiaodiqu": "广州"}'
        - title: "西安"
          payload: '/choose_inform{"baoxiaodiqu": "西安"}'
        - title: "沈阳"
          payload: '/choose_inform{"baoxiaodiqu": "沈阳"}'
    
  utter_ask_baoxiaobumen:
    - text: "请选择您的报销部门"
      buttons:
        - title: "研发中心_成都"
          payload: '/choose_inform{"baoxiaobumen": "研发中心_成都"}'
        - title: "数据中心_福州"
          payload: '/choose_inform{"baoxiaobumen": "数据中心_福州"}'
        - title: "信息中心_福州"
          payload: '/choose_inform{"baoxiaobumen": "信息中心_福州"}'
        - title: "信息中心_上海"
          payload: '/choose_inform{"baoxiaobumen": "信息中心_上海"}'
        - title: "数据中心_上海"
          payload: '/choose_inform{"baoxiaobumen": "数据中心_上海"}'
        - title: "数据中心_成都"
          payload: '/choose_inform{"baoxiaobumen": "数据中心_成都"}'
        - title: "研发中心_上海"
          payload: '/choose_inform{"baoxiaobumen": "研发中心_上海"}'
        - title: "研发中心_福州"
          payload: '/choose_inform{"baoxiaobumen": "研发中心_福州"}'
        - title: "数字卓越中心_上海"
          payload: '/choose_inform{"baoxiaobumen": "数字卓越中心_上海"}'
        - title: "数字卓越中心_福州"
          payload: '/choose_inform{"baoxiaobumen": "数字卓越中心_福州"}'
        - title: "技术与质量管理中心_上海"
          payload: '/choose_inform{"baoxiaobumen": "技术与质量管理中心_上海"}'
        - title: "技术与质量管理中心_福州"
          payload: '/choose_inform{"baoxiaobumen": "技术与质量管理中心_福州"}'
        - title: "本部管理处室"
          payload: '/choose_inform{"baoxiaobumen": "本部管理处室"}'
    
  utter_ask_receive:
    - text: "是否有接待？"
      buttons:
        - title: "是"
          payload: '/choose_inform{"receive": "是"}'
        - title: "否"
          payload: '/choose_inform{"receive": "否"}'
  
  utter_ask_ruzhudi:
    - text: "请输入您的入住地，多个城市用英文分号分隔"
    
  utter_ask_chengjicishu:
    - text: "请输入您的乘机次数，数字即可"
    
  utter_ask_chuxingren:
    - text: "请输入出行人姓名与node_id（英文逗号分隔），如: 张三, 011111"
  
  utter_ask_person_level:
    - text: "请选择出行人行员等级"
      buttons:
        - title: "8级及8级以下"
          payload: '/choose_inform{"person_level": "8级及8级以下"}'
        - title: "9-12级"
          payload: '/choose_inform{"person_level": "9-12级"}'
        - title: "13级"
          payload: '/choose_inform{"person_level": "13级"}'
        - title: "14级以上"
          payload: '/choose_inform{"person_level": "14级以上"}'
          
  utter_ask_banliyijian:
    - text: "请输入办理意见"
    
  utter_ask_nextnode:
    - text: "请选择下一处理步骤"
      buttons:
        - title: "处室负责人审核"
          payload: '/choose_inform{"nextnode": "处室负责人审核"}'
        - title: "部门成员办理"
          payload: '/choose_inform{"nextnode": "部门成员办理"}'
        - title: "部门负责人审核"
          payload: '/choose_inform{"nextnode": "部门负责人审核"}'
        - title: "办理"
          payload: '/choose_inform{"nextnode": "办理"}'
    
  utter_ask_nextperson:
    - text: "请输入下一处理人姓名与node_id（英文逗号分隔），如: 张三, 011111"
    
  utter_ask_is_affirm:
    - text: "确认进行交办吗？"
      buttons:
        - title: "是"
          payload: '/choose_inform{"is_affirm": "是"}'
        - title: "否"
          payload: '/choose_inform{"is_affirm": "否"}'

  utter_ask_meeting_schedule_time:
    - text: "请描述会议室预定时间，如：明天早上9点-11点"

  utter_ask_meeting_start_time:
    - text: "请输入会议开始时间"
  
  utter_ask_meeting_end_time:
    - text: "请输入会议结束时间"

  utter_ask_meeting_start_date:
    - text: "请输入会议开始日期"
  
  utter_ask_meeting_end_date:
    - text: "请输入会议结束日期"

  utter_ask_meeting_name:
    - text: "请输入会议名称"

  utter_ask_meeting_topic:
    - text: "请输入会议议题"

  utter_default:
    - text: "没听懂，请换种说法吧~"
  
  utter_jiaoban_success:
    - text: "已帮您交办了~"
  
  utter_trip_hotel_recommend:
    - text: "帮您推荐入住地 {ruzhudi} 的协议酒店如下:"
    
  utter_trip_flight_recommend:
    - text: "帮您推荐 {start_time} 到 {end_time}, 从 {start_address} 到 {end_address} 的飞机行程如下:"
  
  utter_wrong_start_time:
    - text: "日期或时间不合法！"
  
  utter_wrong_end_time:
    - text: "日期或时间不合法！"

  utter_wrong_start_address:
    - text: "地点不合法！"
  
  utter_wrong_end_address:
    - text: "地点不合法！"
    
  utter_wrong_trip_type:
    - text: "请按提示选择正确的出差类型"
  
  utter_wrong_tiaoxian:
    - text: "请按提示选择正确的条线"
    
  utter_wrong_baoxiaodiqu:
    - text: "请按提示选择正确的报销地区"
    
  utter_wrong_receive:
    - text: "请按提示选择是否有接待"
    
  utter_wrong_baoxiaobumen:
    - text: "请按提示选择正确的报销部门"
    
  utter_wrong_it_item_num:
    - text: "项目呈批件号不合法！"
    
  utter_wrong_fin_item_num:
    - text: "财务项目编号不合法！"
    
  utter_wrong_nextnode:
    - text: "请按提示选择正确的下一处理步骤"
    
  utter_wrong_person_level:
    - text: "请按提示选择正确的行员等级"
  
  utter_wrong_chengjicishu:
    - text: "乘机次数不合法！"
    
  utter_wrong_empty_answer:
    - text: "不可输入空白信息"
  
  utter_wrong_is_affirm:
    - text: "请先进行确认是否交办哦。"
    
  utter_ask_continue:
    - text: "请问您还要继续进行本次申请吗?"
  
  utter_ask_abandon:
    - text: "请问您确定要放弃本次申请吗?"
  
  utter_noworries:
    - text: "不用客气 :)"
    - text: "没事啦"
    - text: "不客气哈，都是老朋友了 :)"
